#!/usr/bin/env python3
import os
import cgi

print("Content-Type: text/html\n")

form = cgi.FieldStorage()
name = form.getvalue("name", "Anonymous")

print(f"""<!DOCTYPE html>
<html>
<head><title>CGI Response</title></head>
<body>
  <h1>Hello, {name}!</h1>
  <p>This response was generated by a Python CGI script.</p>
  <a href="/">Back to Home</a>
</body>
</html>
""")
