/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   StaticFileSource.cpp                               :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: auspensk <auspensk@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/04/29 10:20:27 by auspensk          #+#    #+#             */
/*   Updated: 2025/05/27 16:40:13 by auspensk         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "StaticFileSource.hpp"

StaticFileSource::StaticFileSource(const std::string &target, const ServerConfig &serverConfig, Location const *location)
	: Source(target, serverConfig)
	, _generated(false){
	_location = location;
	checkIfDirectory();
	if (!_generated && !checkIfExists(_target)){
		std::cout << "I shouldn't be here" << std ::endl;
		_code = 404;
		getErrorPage(404);
	}
	if (!_generated){
		_fd = open(_target.c_str(), O_RDONLY);
		struct stat st;
		stat(_target.c_str(), &st);
		_size = st.st_size;
		defineMimeType();
	}
}

StaticFileSource::~StaticFileSource(){
	close(_fd);
}

void StaticFileSource::readSource(){
	if (_bytesToSend > 0 || _generated)
		return;
	_body.clear();
	_body.resize(_serverConfig.getBufferSize());
	_offset = 0;
	ssize_t readSize = read(_fd, _body.data(), _serverConfig.getBufferSize());
	if (readSize < 0)
		throw Source::SourceException("Could not read from static source file");
	_bytesToSend = readSize;
	_body.resize(readSize);
}

bool StaticFileSource::indexExists(const std::vector<std::string> &indexes, const std::string &root){
	for (size_t i = 0; i < indexes.size(); ++i){
		std::string target = root + std::string("/") + indexes.at(i);
		if (checkIfExists(target)){
				_target = target;
				return true;
		}
	}
	return false;
}

void StaticFileSource::checkIfDirectory(){
	DIR *dir = opendir(_target.c_str());
	if (!dir)
		return;
	closedir(dir);
	if (!_location){
		if (indexExists(_serverConfig.getIndexPages(), _serverConfig.getRootFolder()))
			return;
		if (_serverConfig.getAutoIndex()){
			if (generateIndex())
				return;
		}
	}
	else{
		if(indexExists(_location->getIndexPages(),_location->getPath()))
				return;
		if (_location->getAutoIndex()){
			if (generateIndex())
				return;
		}
	}
	_code = 403;
	getErrorPage(403);
}

bool StaticFileSource::checkIfExists(std::string &target){
	DIR *dir = opendir(_serverConfig.getRootFolder().c_str());
	if (!dir)
		throw(Source::SourceException("No root folder"));
	closedir(dir);
	if (access(target.c_str(), R_OK))
		return false;
	return true;
}

void StaticFileSource::defineMimeType(){
	int dotAt = _target.find_last_of('.');
	std::string extension = _target.substr(dotAt);
	_mime = _mimeTypes.find(extension)->second;
}

bool StaticFileSource::readDirectories(std::vector<DirEntry> &entries){
	std::cout << "Target: " << _target << std::endl;
	DIR *dir = opendir(_target.c_str());
	if (!dir)
		return false;
	struct dirent *entry;
	while ((entry = readdir(dir)) != NULL){
		std::string name = entry->d_name;
		if (name == "." || name == "..")
			continue;

		std::string full_path = _target + "/" + name;
		struct stat s;
		if (stat(full_path.c_str(), &s) == 0){
			bool is_dir = S_ISDIR(s.st_mode);
			entries.push_back(DirEntry(name, is_dir));
		}
	}
	closedir(dir);
	return true;
}

bool StaticFileSource::generateIndex(){
	std::vector<DirEntry> entries;
	if (!readDirectories(entries))
		return false;
	std::string relativeTarget = _target;
	std::string prefix = _serverConfig.getRootFolder();
	if (relativeTarget.rfind(prefix, 0) == 0)
		relativeTarget.erase(0, prefix.length());

	std::string html = "<html><head><title>Index of " + relativeTarget + "</title></head>";
	html += "<body><h1> This is autogenerated index of " + relativeTarget + "</h1><hr><ul>";
	for (size_t i = 0; i < entries.size(); ++i){
		std::string name = entries[i].name;
		std::string href = relativeTarget + "/" + name;
		if (entries[i].is_directory){
			href += "/";
			name += "/";
		}
		html += "<li><a href=\"" + href + "\">" + name + "</a></li>";
	}
	html += "</ul><hr></body></html>";
	_body.assign(html.begin(), html.end());
	_generated = true;
	_bytesToSend = _body.size();
	_size = _body.size();
	_mime = _mimeTypes.find(".html")->second;
	return true;
}

void StaticFileSource::getErrorPage(int code){
	// doesn't handle cases when error directive uses external URLs, like: error_page 404 https://example.com/notfound.html
	// I'm not sure if we need to include this feature. Doesn't say anything in the subject
	if (_location && !_location->getErrorPages().empty() && _location->getErrorPages().find(code) != _location->getErrorPages().end())
		_target = _location->getErrorPages().find(code)->second;
	else if (_serverConfig.getErrorPages().find(code) != _serverConfig.getErrorPages().end())
		_target = _serverConfig.getErrorPages().find(code)->second;
	else
		generatePage(code);
}

void StaticFileSource::generatePage(int code){
	_code = code;
	_generated = true;
	std::string html = "<html><head><title> " + _statusCodes.at(code).message + "</title></head>";
	html += "<body><h1>" + _statusCodes.at(code).code + "</h1><hr><ul>";
	html += "<body><h1>" + _statusCodes.at(code).message + "</h1><hr><ul>";
	html += "<body><h2>" + _statusCodes.at(code).description + "</h2><hr><ul>";
	html += "</ul><hr></body></html>";
	_body.assign(html.begin(), html.end());
	_generated = true;
	_bytesToSend = _body.size();
	_size = _body.size();
	_mime = _mimeTypes.find(".html")->second;
}

char *StaticFileSource::getBufferToSend(){
	readSource();
	return readFromBuffer();
}
